openapi: 3.0.3
info:
  title: KOW API
  version: 1.0.0
  description: KOW API for authentication and core resources
paths:
  /auth-jwt/token/:
    post:
      operationId: auth_jwt_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - auth-jwt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /auth-jwt/token/refresh/:
    post:
      operationId: auth_jwt_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - auth-jwt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /auth-jwt/user:
    get:
      operationId: auth_jwt_user_retrieve
      tags:
      - auth-jwt
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /core/medications:
    get:
      operationId: core_medications_retrieve
      description: Get a list of all medications
      tags:
      - core
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /core/pharmacies:
    get:
      operationId: core_pharmacies_retrieve
      description: Get all pharmacies
      tags:
      - core
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /core/pharmacies/{id}:
    get:
      operationId: core_pharmacies_retrieve_2
      description: Get a single pharmacy's details or update that pharmacys enrollment
        details
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - core
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: core_pharmacies_update
      description: Get a single pharmacy's details or update that pharmacys enrollment
        details
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - core
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /core/pharmacies/{id}/pharmacists:
    get:
      operationId: core_pharmacies_pharmacists_retrieve
      description: Get all pharmacists based on a particular pharmacy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - core
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /core/pharmacists:
    post:
      operationId: core_pharmacists_create
      description: Create a pharmacist (which will accept a pharmacy field as input).
      tags:
      - core
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /core/pharmacists/{id}:
    put:
      operationId: core_pharmacists_update
      description: Update or delete a pharmacist
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - core
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: core_pharmacists_destroy
      description: Update or delete a pharmacist
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - core
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /core/requests:
    post:
      operationId: core_requests_create
      description: Create a request. Here we will need to also trigger the API call
        to twilio to send our mass sms
      tags:
      - core
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
