# Generated by Django 4.1.3 on 2022-12-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_medication_name_request_med_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="med_strength",
            field=models.CharField(
                error_messages={"blank": "Please fillout the medication strength"},
                max_length=200,
            ),
        ),
    ]
