# Generated by Django 4.1.3 on 2022-12-18 21:08

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_request_bin_alter_request_med_strength_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="strength",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=api.models.Medication.strength_default,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="med_strength",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
