# Generated by Django 4.1.3 on 2022-12-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_medication_strength_alter_request_med_strength"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="med_name",
            field=models.CharField(
                error_messages={"blank": "Medication name cannot be blank"},
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="med_strength",
            field=models.CharField(
                blank=True,
                error_messages={"blank": "Medication strength cannot be blank"},
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="quantity",
            field=models.CharField(
                error_messages={"blank": "Quantity cannot be blank"}, max_length=200
            ),
        ),
    ]
