# Generated by Django 4.1.3 on 2023-03-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_request_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="user_type",
            field=models.CharField(max_length=200),
        ),
    ]
