# Generated by Django 4.1.3 on 2023-04-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_pharmacy_contact_email_pharmacy_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="signature",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
