# Generated by Django 4.1.3 on 2023-04-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_pharmacy_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="delivery_status",
            field=models.CharField(default="", max_length=200),
        ),
    ]
