# Generated by Django 4.1.3 on 2023-04-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_request_delivery_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="signed_agreement_admin",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
