# Generated by Django 4.1.3 on 2023-04-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_pharmacy_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="initial_rate",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
