# Generated by Django 4.1.3 on 2023-05-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_medication_isspecialty"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="additional_language",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="isDelivery",
            field=models.BooleanField(default=False),
        ),
    ]
