# Generated by Django 4.1.3 on 2022-12-15 01:07

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("brand_name", models.CharField(max_length=200)),
                (
                    "strength",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=api.models.Medication.strength_default,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("medication_name", models.CharField(max_length=200)),
                ("medication_strength", models.CharField(max_length=200)),
                ("quantity", models.CharField(max_length=200)),
                ("bin", models.CharField(max_length=200)),
                ("pcn", models.CharField(max_length=200)),
                ("rxgroup", models.CharField(max_length=200)),
                ("isInsurance", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="pharmacist",
            old_name="pharmacy_name",
            new_name="pharmacy",
        ),
        migrations.AlterField(
            model_name="pharmacist",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pharmacist",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="zipcode",
            field=models.CharField(max_length=30),
        ),
    ]
