# Generated by Django 4.1.3 on 2022-12-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_request_med_strength"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="bin",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="request",
            name="med_strength",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="request",
            name="pcn",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="request",
            name="rxgroup",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
